description: 'IOs - AdjectiveOutput: A Pydantic BaseModel subclass that has ''adjective''
  field of type ''str''. NameCombinationOutput: A Pydantic BaseModel subclass that
  has ''combined_name'' field of type ''str''. NameInput: A Pydantic BaseModel subclass
  that has ''name'' field of type ''str''.'
name: SimpleSammy
parameters: {}
