description: A Yeager Component that takes the 'adjective_list' output from the FetchAdjectives
  component as an input, and randomly selects an adjective from the list, based on
  the inputted `name` from the user. The selected adjective is returned and stored
  in the 'adjective' output field.
input-class: RandomAdjectiveInputDict
name: RandomAdjective
output-class: RandomAdjectiveOutputDict
parameters: {}
